# Configurations
title: 雨坂先生の高校公民問題集
longtitle: 雨坂先生の高校公民問題集
email: teacheramesaka@gmail.com
author: 雨坂上善
description: >- # this means to ignore newlines until "baseurl:"
  高校公民科（公共、政治経済、倫理）の過去問題集。主にセンター試験、共通テストから持ってきてます。今のところ政治経済ばっかり。
baseurl: "/hsworkbookcivics"
url: "https://teacheramesaka.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: teacheramesaka
github_username:  teacheramesaka

version:          1.0
gitbook_version:  3.2.3

rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
